<?php

/**
 * @file
 */

/**
 * Implementation of hook_init().
 */
function statements_init() {
  // Using arg() instead of menu_get_item(). Rumor has it menu_get_item
  // can occassionally cause WSOD.
  // We make sure arg(2) is empty so we do not redirect on edit or other
  // node sub pages.
  if (arg(0) == 'node' && is_numeric(arg(1)) && arg(2) == '') {
    $node = node_load(arg(1));
    if ($node->type == 'statement') {
      drupal_goto('node/'. $node->field_article['und'][0]['nid']);
    }
  }
}

function statements_query_views_articles_statements_alter(QueryAlterableInterface $query) {
  $query->addJoin('LEFT', 'votingapi_cache', 'votes', 'node.nid = votes.entity_id AND votes.entity_type = :type AND votes.function = :func', array(':type' => 'node', ':func' => 'sum'));
  $query->orderBy('COALESCE(votes.value, 0)', 'DESC');
}